Repository pixel-pals/web-app, pull requests merged in 2019-02, with the labels that each got.

#19 Add basic headings
  .editorconfig
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  _config.yml
  css/grid.css
  css/main
  css/modules.css
  css/theme.css
  css/type.css
  images/logo-16.svg
  images/logo-32.svg
  images/logo-64.svg
  images/logo.svg
  index.html
  ruby-version
Labels: bug, dev

#24 practice
  index.html
Labels: dev

#26 Buttons
  _patterns/button/buttons.css
  _patterns/button/buttons.html
  css/theme.css
Labels: design, dev

#27 this commit creates the cards
  Gemfile.lock
  _patterns/cards/cards.css
  _patterns/cards/cards.html
  _patterns/cards/config.yml
  images/breakfast.jpg
Labels: design

#31 Banner
  _patterns/banner/banner.css
  _patterns/banner/banner.html
  images/breakfast-banner.jpg
Labels: design, dev

#32 design the nav bar
  _patterns/nav/nav.css
  _patterns/nav/nav.html
  images/customize.svg
  images/favourite.svg
  images/home.svg
  images/search.svg
Labels: design, dev

#35 Nav bar edits
  _patterns/banner/config.yml
  _patterns/button/config.yml
  _patterns/nav/config.yml
  _patterns/nav/nav.css
  _patterns/nav/nav.html
Labels: design, dev
